### ISSUE TITLE
mysql 5.0.51a-3 无法连接

### ISSUE THREAD

**Issue by freeAhao** [TheKingOfDuck/MySQLMonitor#9]
Caused by: com.mysql.cj.exceptions.UnableToConnectException: CLIENT_PLUGIN_AUTH is required
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:114)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1342)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)

依赖的jdbc驱动版本不支持了吧，有办法兼容吗

**Comment by TheKingOfDuck** [comment]
> Caused by: com.mysql.cj.exceptions.UnableToConnectException: CLIENT_PLUGIN_AUTH is required
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
> at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
> at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:114)
> at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1342)
> at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
> at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
> at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
> 
> 依赖的jdbc驱动版本不支持了吧，有办法兼容吗

目前采用的是8.0的驱动  是可以向下兼容的 jdbc url格式不同也有处理的逻辑 按理应该可以 报错是冲突了

想找个mysql5.0的环境试试来着 电脑mac的 没有很方便的工具切换这些 调试不方便 应该改一下pom中的驱动版本 再重新打包就可以了

**Comment by freeAhao** [comment]
修改jdbc驱动版本后数据库连接上了，但是开启日志失败

```
[15:17:09] Database version: 5.0.51a-3ubuntu5-log
java.sql.SQLException: Unknown system variable 'general_log'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1056)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3361)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3295)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1852)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1975)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2470)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2399)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1218)
	at net.thekingofduck.MySQLMonitor.main(MySQLMonitor.java:122)
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mysql.general_log' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
	at com.mysql.jdbc.Util.getInstance(Util.java:378)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3361)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3295)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1852)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1975)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2470)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2399)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1218)
	at net.thekingofduck.MySQLMonitor.main(MySQLMonitor.java:170)
```

根据网上资料 mysql < 5.1.29 需要修改my.conf配置文件并重启服务开启日志，也不存在日志表msyql.general_log
应该只能进系统读日志文件，也许可以通过load_file('/xxx/xxx.log')

关闭issue了，这个靶机(metasploit)环境的mysql版本太老辣。
